### ISSUE TITLE
[Test] Remover um AnswerPost

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#102]
- Checar se após enviar um AnswerPost para deletar, ele é de fato removido do banco.

**Comment by fbormann** [comment]
não tem commit associado com esta issue, quais arquivos tu modificou? @filipecmedeiros

**Comment by filipecmedeiros** [comment]
/forum/test_model_answerPost.py

**Comment by jailson-dias** [comment]
ok
