### ISSUE TITLE
Send e-mail with hashed link

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#109]
Mandar um link para uma URL específica de submissão de nova senha para o e-mail do usuário.

**Comment by gbl3** [comment]
Não tem nenhum commit associado, tu resolveu a Issue em qual commit?

**Comment by ifac0** [comment]
"alteração no setting para encaminhar o email #58"

Foi nesse commit, tem como associar @gbl3 ?

**Comment by jailson-dias** [comment]
ok
