### ISSUE TITLE
[Template/View] Criar Enquete

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#115]
- Ter uma URL direta para a Enquete.
- Mensagem de sucesso caso a enquete seja criada com sucesso
- Mensagem de erro caso algum campo seja preenchido errado.

**Comment by jailson-dias** [comment]
Não é possivel de criar uma URL para este template, pois ele abre como um modal, assim ele depende de uma outra view para ser pre carregada.

**Comment by jailson-dias** [comment]
Isto está no commit "Criado o templete de atualizar enquete #77" da issue #77
