### ISSUE TITLE
[Model] Link

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#119]
Mover Model de Link de Courses para Link App

**Comment by filipecmedeiros** [comment]
Reviewing

**Comment by filipecmedeiros** [comment]
The model isn't creating a table in database

**Comment by gbl3** [comment]
@filipecmedeiros  roda manualmente, aqui funcionou assim... 

Comandos: python manage.py makemigrations links
depois : python manage.py migrate links

**Comment by filipecmedeiros** [comment]
Done

**Comment by gbl3** [comment]
Reopened because image field will be added

**Comment by jailson-dias** [comment]
ok
