### ISSUE TITLE
[Template/View] Criar Link

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#120]
- Inserir valores em campos
- Retornar mensagem de sucesso
- Retornar mensagem de erro (e apontar o erro na UI).
- Ter uma URL específica para isto

**Comment by ifac0** [comment]
![6](https://cloud.githubusercontent.com/assets/17273665/19790297/98e48ea0-9c8d-11e6-8610-1b21b84a2077.png)

@gbl3 botão com o nome errado

**Comment by ifac0** [comment]
ok

**Comment by jailson-dias** [comment]
@gbl3 esse form não está no padrão do restante
como pode ser visto nesta imagem ![link ](https://cloud.githubusercontent.com/assets/12815859/19826428/8dc7a1d2-9d60-11e6-8025-f5fea921b6fb.png), o certo era pra ser como está em file, assim:
![file create](https://cloud.githubusercontent.com/assets/12815859/19826435/de4a3296-9d60-11e6-8abf-02c4faae422c.png)

- E o botão de cancel tb não está no padrão, era pra ser como está em file

**Comment by filipecmedeiros** [comment]
Ok
