### ISSUE TITLE
[Test] Criar Link

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#123]
- Mensagem de OK caso os campos sejam inseridos corretamente.
- Para todos os possíveis campos, mensagem de OK ao inserir dados errados e o objeto não seja criado.

**Comment by jailson-dias** [comment]
@gbl3 os testes estão bons, só que você está testando com um usuário system admin, era pra está testando com usuários de professor e aluno.

**Comment by gbl3** [comment]
@jailson-dias deixo o teste que tá e adiciono o teste com professor e aluno, ou deixo só o de professor e aluno?

**Comment by ifac0** [comment]
![4](https://cloud.githubusercontent.com/assets/17273665/19790184/982bb548-9c8c-11e6-9ed1-460bb6b8a6eb.png)

@gbl3 tem um erro no test de update
