### ISSUE TITLE
[Test] Modificar Arquivo

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#130]
- Modificar um arquivo através do upload de um arquivo com mesmo nome mas tamanho diferente.
- Checar se o tamanho e a extensão dos arquivos foram modificados, se sim, OK. Senão, mensagem de erro correspondente.

**Comment by jailson-dias** [comment]
@ailsoncgt

- falta os casos de fracasso, que esta faltando colocar o arquivo para criar ou o arquivo é muito grande, e tb testar que um professor do curso pode editar ou deletar o file, mas um aluno ou professor de outro curso não pode editar ou deletar este file
- o endereço do arquivo está absoluto "open('/home/ailson/Pictures/update.png', 'rb')", assim só pegando no seu PC, ele precisa ser relativo para funcionar em qualquer PC
- existe uma pasta tests e um arquivo tests.py, aí quando eu executo test file dá erro, pois ele não sabe qual o teste executar, precisa apagar o arquivo tests.py

**Comment by jailson-dias** [comment]
ok
