### ISSUE TITLE
[Template/View] Remover arquivo

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#134]
- Deve haver uma URL para tal template. 
- Uma View (seja function ou CBV)
- Nesta tela deve ser possível saber o nome do arquivo, a qual topic/course pertence
- Ter a opção de deletar
- Ter a opção de cancelar (antes do processo inicializar)
- Ter um link para o arquivo.

**Comment by jailson-dias** [comment]
ok
