### ISSUE TITLE
[Template/View] Categoria de Cursos

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#136]
Listar cursos por categoria que o aluno está cadastrado

**Comment by jailson-dias** [comment]
@matheuslins tem que fazer com que não fique exibindo todas as categorias que tem algum curso para não ficar como nessa [imagem](http://projetoamadeus.esy.es/img/categoias.png), tu coloca para exibir só as que tem mais cursos por exemplo, para não ficar tanta categorias e não ficar dando nem pra ver o nome direito e também esse campo de pesquisar não está funcionando

**Comment by matheuslins** [comment]
Entendi, vou ajustar. Em relação ao filtro, acho melhor criar outra issue

**Comment by jailson-dias** [comment]
@matheuslins nesta tela no menu actions tem o botão "replicate course", só que ele não faz sentido de está aí, pq o usuário não está cendo nenhum curso para ele replicar, e o botão de "create category" esta em dois lugares, no menu actions e em category, era pra está apenas em um. E o dropdown não esta bem alinhado a direita, era pra está como está o de cursos na página de listar cursos.
