### ISSUE TITLE
[Template] Register User

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#14]

**Comment by juliotoscano** [comment]
Revisado #14

**Comment by fbormann** [comment]
Tem dois botões: "salvar" e "register", isto confude o usuário.
- não tem mensagem de sucesso caso o registro tenha funcionado.

**Comment by fbormann** [comment]
O template melhorou muito mas ainda falta ter um * quando o campo for obrigatório. Procurei por aqui https://docs.djangoproject.com/en/1.10/ref/models/fields/ pra ajudar mas só tinha falando sobre a opção "Blank" do model( se ela for falsa, se torna "required") mas acho  se tu procurar no template "users/create.html" por um atributo de field chamado "required", tu pode concatenar as strings field.name+"*". Saca lá, coloquei em refactoring só por isso mesmo.

**Comment by ailsoncgt** [comment]
Bem visto, @fbormann .
Saca lá agora...

**Comment by thiagosoara** [comment]
Problemas:

1. Register user: datepicker. usar o padrão do frontend definido por uxdesign(veja lá no repositório)
2. Faltando CPF mask
3. Faltando Phone Mask
4. Não mostrou mensagem de usuário inserido com sucesso!

**Comment by gbl3** [comment]
@thiagosoara acabei de testar e o cpf mask tá funcionando e também está mostrando a mensagem de usuario inserido com sucesso!

![image](https://cloud.githubusercontent.com/assets/18217042/19060225/8567114c-89bc-11e6-969d-f4d10a4a4528.png)

**Comment by thiagosoara** [comment]
@gbl3 @ailsoncgt 
Verdade, só está faltando mesmo os pontos 1 e 3 que citei então.

**Comment by thiagosoara** [comment]
Quando o cara não cadastra uma imagem não aparece uma imagem padrão. Olha como fica(favor colocar uma default image):

![image](https://cloud.githubusercontent.com/assets/766210/19081492/d9b981a2-8a30-11e6-82cb-364a65245def.png)

**Comment by Zambom** [comment]
O phone mask não considera o fato do telefone ter apenas 8 dígitos.

**Comment by ailsoncgt** [comment]
@Zambom , o mask é para celular, já que é um contato pessoal.

**Comment by Zambom** [comment]
Mesmo assim, ainda existem números de celular sem o 9º digito...

**Comment by ailsoncgt** [comment]
Sabia não @Zambom ... kkkk vou ajeitar
Valew

**Comment by ailsoncgt** [comment]
@Zambom , uma dúvida ... o que seria admitir celular com 8 dígitos ...? Sério kkk

**Comment by fbormann** [comment]
@ailsoncgt , acho que ele quis dizer os celulares de outros estados que não possuem 9 dígitos ainda, apesar que não sei se isso já foi modificado em todos os outros estados, entendeu?

**Comment by ailsoncgt** [comment]
Sim entendi, só n entendi como ficaria na máscara porque o máximo que ele aceita é com 9 dígitos(que já inclui o caso de possuir somente 8 dígitos).

Será o hífen '-' ,@Zambom ?

**Comment by Zambom** [comment]
Exatamente o que @fbormann falou... Geralemente nas máscaras de telefone depois que você coloca o código de área se o seu número tiver apenas 8 dígitos você dá um espaço, caso contrário voce digita os números normalmente...

**Comment by Zambom** [comment]
No caso o número com 8 digitos ficaria assim: (81) 1234-5678

**Comment by jailson-dias** [comment]
ok
