### ISSUE TITLE
[Template/View] Criar categoria de Curso

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#142]
- Ter uma URL responsável pela criação de um CourseCategory
- Um template(ou não, somente um botão em outro template) que envie a informação para esta URL/View.

**Comment by jailson-dias** [comment]
@matheuslins não está no padrão dos outros templates do projeto

**Comment by jailson-dias** [comment]
@matheuslins o botão de save está fora do padrão do projeto, ele tem que fica como está o botão verde de edit message no forum.

**Comment by jailson-dias** [comment]
ok
