### ISSUE TITLE
[Template/View] Modify Notifications.html to keep data 

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#159]
I need to keep the data from where I should keep adding notifications from.

**Comment by jailson-dias** [comment]
@fbormann está faltando os commits desta atividade.

**Comment by fbormann** [comment]
Poxa, ele ficou em outra atividade. A descrição também ficou ruim mas era basicamente com que as notificações salvassem os dados vindo do context (para ser adicionado ao html). O que foi feito. (Quando clico em "See more")

**Comment by jailson-dias** [comment]
ok
