### ISSUE TITLE
[Template] Home Page

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#16]

**Comment by Zambom** [comment]
No template da home o sidebar (que possui um button-group) não está adaptado para a responsividade... É como se esse elemento tivesse um width fixo, dado que ele não herda o width do col-sm-* definido no elemento "pai"...

**Comment by fbormann** [comment]
Zambom, tu confirmou isso dando resize? se sim, era bom reportar ao @juliotoscano , que é o  Scrum Master dessa sprint em uxdesign.

**Comment by Zambom** [comment]
@fbormann estava vendo aqui agora, a questão é a maneira como os blocos estão divididos... Se colocar todos os três blocos (sidebar, content e rightbar) com o mesmo tamanho (no caso 4 colunas) funciona normal...

**Comment by fbormann** [comment]
hm... a minha dúvida é se esse modelo "4-4-4" ficaria esteticamente legal. Um sidebar do tamanho do bloco principal e tal? O modelo "2-6-4" não tá funcionando mesmo?.

**Comment by Zambom** [comment]
De fato esse modelo "4-4-4" fica meio estranho... O que acontece é que a partir da configuração do "md" (se eu não me engano) a col-6 começa a "sobrescrever" a col-2... Acredito que mudando o elemento da sidebar resolveria, mas a estética talvez não ficasse legal por ficar pequeno demais...

Uma coisa que eu não entendi muito bem é o sentido dessa rightbar...

**Comment by fbormann** [comment]
Ahh zambom, se quiser, a gente pode sentar amanhã, é porque a gente quer dividir o "conteúdo" de cada page em três colunas. Foi algo decidido pela galera de #uxdesign. Eu posso te explicar de boas.

**Comment by Zambom** [comment]
Ah entendi...

**Comment by fbormann** [comment]
O header já foi modificado para ficar 100% correto, mas  existe um problema:
- o texto "Notifications" não existe no cento.

**Comment by fbormann** [comment]
Review 100% completa. Atividade movida para Done.
