### ISSUE TITLE
Modify Columns structure on all templates

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#170]

**Comment by ailsoncgt** [comment]
A página 'Manage Users' não tem opção Home' no menu. Acho interessante ter, apesar de poder regrassar a home clicando na logo
Segue o print
![screenshot from 2016-10-10 12-25-46](https://cloud.githubusercontent.com/assets/18018868/19241367/b599caee-8ee4-11e6-8f23-6820733fa364.png)

**Comment by fbormann** [comment]
Certo, posso modificar isso @ailsoncgt. Alguém mais do @amadeusproject/backend concorda?

**Comment by ailsoncgt** [comment]
'Course detail' também não tem.
Acho que é só colocar no template 'base.html' que resolve.

![screenshot from 2016-10-11 09-56-03](https://cloud.githubusercontent.com/assets/18018868/19270987/1d3d49fa-8f99-11e6-97fd-7bdae8b1e7de.png)

**Comment by fbormann** [comment]
@ailsoncgt  tu pode revisar aqui? Acho que fiz a tarefa direito.

**Comment by jailson-dias** [comment]
@fbormann como @ailsoncgt falou acho que esse menu deveria está no base, pois é uma coisa que está em quase todas as telas e também seria bom para ter um padrão e não ficar o mesmo menu com varios nomes (menu em course, subjects entre outros, profile em profile e varios outros nomes em diferentes telas do projeto)

**Comment by fbormann** [comment]
O problema é que base.html é usado em vários lugares, como por exemplo, em login.html, que não tem um menu lateral esquerdo, ele pode até ser um bloco, assim o filho pode ter ou não, o que ficaria interessante, o que acha? @jailson-dias

**Comment by jailson-dias** [comment]
@fbormann o template de registrar usuário não está bem dividido na tela, ele está mais a direita, e além disso ele está sendo feito com base em "col-xx-*" do bootstrap, assim tendo umas 50 col dentro de uma mesma row fazendo que ele ainda fique pior dependendo do tamanho da tela.

**Comment by jailson-dias** [comment]
ok
