### ISSUE TITLE
[Template/View] Modificar template base

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#172]
- Remover a coluna right_side_bar de todos os templates files
- Modificar a estrutura de colunas do base.html

**Comment by ailsoncgt** [comment]
"Modificar a estrutura de colunas do bas.html". como era pra ficar @fbormann ?

**Comment by fbormann** [comment]
Desculpa @ailsoncgt , esqueci de colocar, era somente retirar o bloco "rightbar" e dar um resize no bloco "content" pra ficar ocupando o espaço que ficou vazio.

**Comment by ailsoncgt** [comment]
valew @fbormann .
