### ISSUE TITLE
[Template/View] Editar categoria de Curso

### ISSUE THREAD

**Issue by matheuslins** [amadeusproject/amadeuslms#173]

**Comment by jailson-dias** [comment]
não foi feito

**Comment by matheuslins** [comment]
Foi feita, só que está dentro do editar curso. Como cada curso tem uma categoria, se o usuário quiser editar a categoria de um determinado curso, é ir na opção de editar curso. Não faz sentido ter uma url só par isso

**Comment by jailson-dias** [comment]
@matheuslins o botão de save está fora do padrão do projeto, ele tem que fica como está o botão verde de edit message no forum.

**Comment by jailson-dias** [comment]
ok
