### ISSUE TITLE
[Template/View] Paginação dos Cursos

### ISSUE THREAD

**Issue by matheuslins** [amadeusproject/amadeuslms#176]

**Comment by jailson-dias** [comment]
@matheuslins a páginação quando é recarregado a página exibe doi cursos por página, más se eu clicar em uma categoria exibe 3 cursos por página, era pra aparecer 20 ou 15 por página independente de o usuário clicar em categoria ou atualizar a página.

**Comment by jailson-dias** [comment]
@matheuslins Mesmo o aluno não estando em todos os cursos o pagination aparece como se ele tivesse em todos os cursos, era pra aparecer apenas o necessário para exibir os cursos que ele está.

**Comment by jailson-dias** [comment]
@matheuslins ainda está com o mesmo erro.

**Comment by fbormann** [comment]
@matheuslins  saiu do projeto, então estou removendo suas issues.
