### ISSUE TITLE
[Template/View] Listar Categorias

### ISSUE THREAD

**Issue by matheuslins** [amadeusproject/amadeuslms#179]

**Comment by jailson-dias** [comment]
@matheuslins está tela não foi feita, está a mesma que @Zambom fez e ela precisa ser listada em cards com um link para a categoria no nome dela e não no icone do olho, precisa ter o dropdown com as opções de editar e deletar e também não é pra exibir o slug da categoria ao lado do nome dela isso é uma coisa que o back vai usar pra exibir a categoria, assim não faz sentido o usuário ver este texto.

**Comment by jailson-dias** [comment]
@matheuslins está faltando os commits desta atividade

**Comment by jailson-dias** [comment]
ok
