### ISSUE TITLE
[BUG] Manage user

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#184]
- clicar search também retorna o usuário atual, deveria retornar apenas os outros usuários
- esta pesquisando apenas pelo nome, deveria pesquisar por nome e login
- botão de deletar está verde, era pra ser vermelho
- botão de search está fora do padrão do projeto, era pra ser uma lupa
- foto do usuário não está sendo cortada no centro, ela esta sendo comprimida, era pra ser cortada no centro
- data de nascimento não está no formato certo para ser reconhecido pelo django, ele está trocando o dia com o mês.

**Comment by ailsoncgt** [comment]
@jailson-dias , data de nascimento não é nessa tela('Manage user')

**Comment by jailson-dias** [comment]
@ailsoncgt só faltou concertar a foto, ela aí está ficando comprimida.

**Comment by Zambom** [comment]
@ailsoncgt Coloquei uma foto retangular e ela "duplicou" na exibição...
![captura de tela de 2016-10-27 17-54-41](https://cloud.githubusercontent.com/assets/5719854/19785098/8618cbac-9c6e-11e6-82ff-05bd0d724559.png)

**Comment by ailsoncgt** [comment]
Valeu zambom, já sei o que é.

**Comment by jailson-dias** [comment]
@ailsoncgt  No meu tb deu o mesmo problema que deu com Zambom. Dessa issue só está faltando resolver este problema da imagem o restante esta ok.

**Comment by jailson-dias** [comment]
@ailsoncgt o botão de delete do modal não está funcionando e consequentemente não esta deletando o usuário.

**Comment by ailsoncgt** [comment]
@gbl3 , vê esse último erro que @jailson-dias comentou .

**Comment by gbl3** [comment]
@ailsoncgt aqui funcionou... 
![image](https://cloud.githubusercontent.com/assets/18217042/19822419/211487d0-9d42-11e6-8dcd-b9b3224950ea.png)

**Comment by gbl3** [comment]
![image](https://cloud.githubusercontent.com/assets/18217042/19822433/320d8e06-9d42-11e6-9cdc-7e2e48d8a6d7.png)

**Comment by ailsoncgt** [comment]
aqui o delete está sem açao.
Outra coisa, esses botões estão fora do padrão

**Comment by jailson-dias** [comment]
@gbl3 @ailsoncgt aqui o botão de delete do modal esta sem ação, além de ele e o botão de cancelar está fora do padrão do projeto.

**Comment by ailsoncgt** [comment]
@gbl3 , alguma novidade?
Realmente não pegou aqui também!

**Comment by jailson-dias** [comment]
esta faltando só ajeitar a imagem, mas eu vou criar uma issue só para ajeitar estas imagens em todas as telas.
