### ISSUE TITLE
[BUG] Editar Usuario

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#185]
- Campo de data de nascimento quando os dados são carregados do banco eles são exibidos em um formato e quando o usuário seleciona no calendário eles são exibidos de outro (yyyy-mm-dd e dd/mm/yyyy), era pra sempre ser exibido no mesmo formato(dd/mm/yyyy).
- Não tem os campos de titulação, ano, instituição e currículo que estão presentes no profile view, era pra ter todos esses campos.
- Campo de data de nascimento não é obrigatório, más se não for informado dá erro em criar o usuário, deve ser consertado este bug, colocando ele obrigatório ou tratando quando ele não for informado.

**Comment by jailson-dias** [comment]
@ailsoncgt só está errado o campo de data de nascimento que está trocado o dia com o mes, aí se escolher a data com o dia maior que 12 ele vai dá erro, e o outro erro é o do número do telefone que não tem como apagar.

**Comment by jailson-dias** [comment]
@ailsoncgt encotrei outros erros, quando um aluno vai editar o perfil e ele clicar em salvar ele é redirecionado para fazer login e o campo de data de titulação está aceitando letras e era pra aceitar apenas numeros.

**Comment by Zambom** [comment]
@jailson-dias o erro da data já foi concertado... Testei aqui tanto em inglês quanto em português..

**Comment by jailson-dias** [comment]
@Zambom @ailsoncgt esse erro da data eu pensei que era o mesmo que estava dando nas outras telas, só que ele é outro, esse é se a data for depois do dia atual, aí se for pelo menos um dia depois da data atual vai dá o seguinte erro "Can't convert 'datetime.date' object to str implicitly".

**Comment by jailson-dias** [comment]
ok
