### ISSUE TITLE
[BUG] Criar Usuário

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#186]
- Campo de data de nascimento não é obrigatorio, más se não for informado dá erro em criar o usuário, deve ser consertado este bug, colocando ele obrigatório ou tratando quando ele não for informado.
- Os botões de salvar e cancelar não estão no padrão do projeto, era para ser verde e vermelho respectivamente como está em edit message no forum.
- Alerta de campo errado está do meio para o final da tela, era para ser na tela toda.
- Botão de enviar email não funciona, era pra rediecionar para a tela de enviar email.
- Não tem os campos de titulação, ano, instituição e curriculo que estão presentes no profile view, era pra ter todos esses campos.
- data de nascimento não está no formato certo para ser reconhecido pelo django, ele está trocando o dia com o mês.

**Comment by ailsoncgt** [comment]
@jailson-dias, @fbormann e @juliotoscano,  qual a tela de "Enviar email"?

**Comment by juliotoscano** [comment]
Acho que é manage_user ou home admin.

**Comment by ailsoncgt** [comment]
o template @juliotoscano . Não o menu

**Comment by jailson-dias** [comment]
@ailsoncgt
- Os botões de salvar e cancelar não estão no padrão do projeto, era para ser verde e vermelho respectivamente como está em edit message no forum.
- Alerta de campo errado está do meio para o final da tela, era para ser na tela toda.
- Botão de enviar email não funciona, era pra rediecionar para a tela de enviar email.
- Não tem os campos de titulação, ano, instituição e curriculo que estão presentes no profile view, era pra ter todos esses campos.

**Comment by jailson-dias** [comment]
ok
