### ISSUE TITLE
[BUG] View Profile

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#187]
- Imagem do usuário está como elipse, era pra ser cortada no centro e mostrada redonda.
- A logo do amadeus não está aparecendo, era pra aparecer acima do card de profile.
- Status sempre está offline
- Tipo de usuário não está aparecendo, era pra mostra se o usuário é aluno, professor ou admin.
- Titulação sempre é mestrado, era pra pegar a titulação do usuário.
- Ano sempre é 2012, era pra mostra o ano da titulação.
- Instituição sempre é UFPE, era pra mostra a instituição da titulação.
- Curriculo sempre é "-", era pra mostrar um link para o curriculo do usuário caso ele tivesse.
- Botões de edit profile e delete account não estão no padrão do projeto, era para ser vermelho e verde respectivamente como está em edit message no forum.
- Botão de delete account não está funcionando

**Comment by jailson-dias** [comment]
@fbormann o campo de status sempre está vazio e a imagem do perfil do usuario não está sendo cotada, assim dependendo da imagem ela fica uma elipse.

**Comment by fbormann** [comment]
@jailson-dias , checa o negócio da imagem, por favor? e manda por aqui o exmeplo de imagem que tu usou pra achar o erro? não consigo achar de jeito nenhum uma que quebre.

**Comment by jailson-dias** [comment]
esta é a imagem, isto acontece pq a largura é muito maior do que a altura ![quebra](https://cloud.githubusercontent.com/assets/12815859/19912971/2f8b1552-a07d-11e6-8628-1c405bb4031f.png)

**Comment by fbormann** [comment]
beleza, valeu!

**Comment by fbormann** [comment]
@jailson-dias, checa como tá  a imagem agora

**Comment by jailson-dias** [comment]
@fbormann ainda ta do mesmo jeito

**Comment by fbormann** [comment]
@jailson-dias , modifiquei para que as imagens ficassem quadradas, foi a única forma de dar esse resize sem cortar uma imagem grande toda ( o que fica uma droga), para imagens grandes, ou se corta ou dá resize.

**Comment by jailson-dias** [comment]
vou criar uma outra issue para resolver esse problema da imagem
