### ISSUE TITLE
[BUG] Edit Profile

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#188]
- Os botões de salvar e cancelar não estão no padrão do projeto, era para ser verde e vermelho respectivamente como está em edit message no forum.
- Campo de data de nascimento quando os dados são carregados do banco eles são exibidos em um formato e quando o usuário seleciona no calendário eles são exibidos de outra(yyyy-mm-dd e dd/mm/yyyy), era pra sempre ser exibido no mesmo formato(dd/mm/yyyy).
- Não tem os campos de titulação, ano, instituição e currículo que estão presentes no profile view, era pra ter todos esses campos.
- Quando o aluno clica em cancelar dá erro 403 forbidden, era apenas para voltar para View Profile.

**Comment by ailsoncgt** [comment]
Fixed in issue #185 , last commit

**Comment by jailson-dias** [comment]
@ailsoncgt só tem um problema nesta tela, não tem um espaçamento do card para o final da tela, como está em profile.

**Comment by Zambom** [comment]
@ailsoncgt depois de editar o usuário "perde" o status de ativo e o "tipo" que ele se enquadra (aluno, professor)

**Comment by jailson-dias** [comment]
@ailsoncgt encotrei outros erros, além desse que zambom falou, o campo de data de titulação está aceitando letras e era pra aceitar apenas numeros e não dá para apagar o número do telefone e colocar outro.

**Comment by Zambom** [comment]
@ailsoncgt outra coisa: o menu lateral dessa tela mostra o link para adicionar usuário mesmo eu estando logado como aluno... E o breadcrumbs me mostra o link para o Manage Users (Apesar de dar 403 quando eu clico, seria interessante não mostrar para o aluno esse link eu diria...)

**Comment by jailson-dias** [comment]
ok
