### ISSUE TITLE
[Form] Register User

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#19]

**Comment by juliotoscano** [comment]
revisado #19

**Comment by juliotoscano** [comment]
O campo birth day está com o tipo de input errado.

**Comment by fbormann** [comment]
movi o card para "In progress"

**Comment by ailsoncgt** [comment]
Acho que é melhor fazer isso com JS, com o input do django não fica legal.
O que acham?

**Comment by ailsoncgt** [comment]
@juliotoscano e @fbormann , e aí?

**Comment by juliotoscano** [comment]
Ailson, no formulario que eu fiz já tem o tipo do campo birth day certinho. Pega de la
