### ISSUE TITLE
[Template/View] Listar cursos públicos

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#190]

**Comment by filipecmedeiros** [comment]
Pelo que eu falei com @juliotoscano , não tem uma tela específica pra esse template. Vai ficar a tela de cursos normal do aluno cadastrado?

**Comment by jailson-dias** [comment]
@filipecmedeiros está falatando a páginação dos cursos, assim com muitos cursos fica um scroll muito longo, aí é melhor colocar uma páginação e colocar uns 10 cursos por página.

**Comment by jailson-dias** [comment]
@filipecmedeiros o template guest.html não está estendendo de base.html, assim tendo duplicação de código e fazendo com que o botão de logout não apareça no head.

**Comment by filipecmedeiros** [comment]
@jailson-dias Foi proposital ele não herdar do template base.html. Ele dava pau quando você não estava logado e acessava a página. Se o usuário clicasse nos botões de perfil do usuário ou logout quebrava o servidor.

**Comment by filipecmedeiros** [comment]
E vou adicionar a paginação

**Comment by jailson-dias** [comment]
@filipecmedeiros acho que este template tem que ficar parecido com o template de my courses, para não ficar dois templates que fazem praticamente a mesma coisa muito diferentes como está agora

**Comment by filipecmedeiros** [comment]
Ok, vou readaptar

**Comment by jailson-dias** [comment]
ok
