### ISSUE TITLE
[Log] Cursos

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#203]
Aluno e professor
Guardar acesso de usuário aos cursos de uma determinada categoria

**Comment by fbormann** [comment]
@Zambom uma dúvida, porque tu tás salvando tanto o id quanto o slug? Os dois não são identificadores únicos do objeto?

**Comment by Zambom** [comment]
@fbormann naobtenho um motivo específico... É mais pelo costume de trabalhar com o id mesmo...

**Comment by jailson-dias** [comment]
ok
