### ISSUE TITLE
Review de Design (Sprint I - VI)

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#205]
- [x] login
- [x] register user
- [x] reset-password
- [x] reset-password-done
- [x] edit profile
- [x] view profile
- [x] change password
- [x] remove account
- [x] home student
- [x] home course student
- [x] home subject student
- [x] home topic student
- [x] home teacher
- [x] home course teacher
- [x] home subject teacher
- [x] home topic teacher

**Comment by jailson-dias** [comment]
@juliotoscano alguns templates não estão no padrão do projeto, como o template de edit profile, remove account, edit user entre outros.

**Comment by juliotoscano** [comment]
vou verificar isso.

**Comment by fbormann** [comment]
considero fechado, outros bugs deverão ser colocados em suas issues específicas, isso aqui tá genérico demais.
