### ISSUE TITLE
[Log] Setar e colocar todas as possíveis notificações de cada page

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#207]
- [x] Adicionar mensagem para criação, remoção de fórum
- [x] Adicionar mensagem para criação de nova atividade
- [x] Adicionar Mensagem para novo Link
- [x] Adicionar para mensagem à resposta de outro usuário ao post em fórum

**Comment by fbormann** [comment]
As notificações de Poll, Link e qualquer outro que tenha modal, eu redirecionei para o Tópico pois eles não possuem víews específicas.

**Comment by jailson-dias** [comment]
@fbormann no caso de enquete tem sim view como qualquer uma outra tela, assim dá pra vc fazer a mesma coisa que fez nas outras telas e acho que em forum dá pra fazer o mesmo.

**Comment by fbormann** [comment]
Eu já o fiz @jailson-dias

**Comment by jailson-dias** [comment]
ok
