### ISSUE TITLE
[Template/View] Centralizar o form da tela "Register User"

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#208]

**Comment by jailson-dias** [comment]
@fbormann depois que tu centralizou este form surgiu alguns outros erros, como por exemplo o label de data de nascimento está deslocado para a esquerda, entre outros pequenos erros.

**Comment by jailson-dias** [comment]
@fbormann estes erros ainda não foram resolvidos, olha está tela aí e tenta consertar ela.

**Comment by fbormann** [comment]
Aquela quantidade de colunas eram necessárias @jailson-dias por conta do alinhamento e design mesmo. Adicionei tag "row" em volta deles para ficarmos organizados com o padrão do bootstrap

**Comment by jailson-dias** [comment]
@fbormann agora só está faltando ajeitar os botões de save e cancel que não estão no padrão do projeto, era pra ser verde e vermelho respectivamente, como em criar forum, além de quando dá um erro no formulario a mensagem de erro aparece do meio para o final do card, era pra aparecer em todo o card.

**Comment by fbormann** [comment]
@jailson-dias  o erro aparecer em todo o card? como você imagina isso?

**Comment by jailson-dias** [comment]
@fbormann do mesmo jeito que aparece nesta tela 
![erro tela toda](https://cloud.githubusercontent.com/assets/12815859/19876966/a612a06a-9fb9-11e6-8ffa-72e8d85d431a.png)

**Comment by fbormann** [comment]
@jailson-dias  agora que foi, pode dar uma olhada? mudei os ícones de save e cancel também.

**Comment by jailson-dias** [comment]
ok
