### ISSUE TITLE
[Form] Criar form da tela SMTP Manager (com validações)

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#212]

**Comment by jailson-dias** [comment]
@ailsoncgt a validação do campo email host está para uma url
o campo default from email não está com a validação de email, apenas está exigindo uma "@", era pra validação ser [a-z0-9.-]+@[a-z]+.[a-z]+

**Comment by ailsoncgt** [comment]
@jailson-dias 
1. ela é uma url, não?
2. já tem essa validação no back-end. Não pega no seu?

**Comment by jailson-dias** [comment]
@ailsoncgt o primeiro foi erro meu mesmo, agora o segundo quando eu coloco um email do tipo "asd@add" ele não dá erro, más tb não cadastra, aí é só pra resolver isso, para caso o email não for aceito exibir uma mensagem de erro

**Comment by jailson-dias** [comment]
ok
