### ISSUE TITLE
[BUG] Detail Course

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#214]
- Os botões de participantes sempre está redirecionando para "teacher/course_participants_teacher.html", más está url não existe, deveria redirecionar para uma tela com os alunos do curso.
**- Tem um botão de "todos" no topo da página que não faz nada, acho que deve ser retirado.**
- **No menu de actions tem o botão de criar topic, só que não tem como criar um topico para todos os subjects, assim acho que ele deve ser removido.**
**- O botão create subject sempre está redirecionando para "#", deveria redirecionar para a página de criar subject.**
**- Todos os botões do menu actions não estão funcionando, eles deveria está redirecionando para as suas respectivas paginas.**
- **O botão remover subject do dropdown esta exibindo um modal fora do padrão do projeto( o padão no titulo tem o nome do subject e em baixo tem os botões de confirmar e cancelar).**
- **No modal de deletar subject quando clica em confirmar ele sempre redireciona para "http://127.0.0.1:8080/html/screens/users/teacher/home_course_teacher.html", deveria deletar o subject.**
- No dropdown de cursos apenas está funcionando o botão de editar, era pra todos estarem funcionando.
- No dropdown de subject o botão de replicate não está funconando, deveria replicar o subject.

**Comment by fbormann** [comment]
@matheuslins  saiu do projeto, então estou removendo suas issues.
