### ISSUE TITLE
[BUG] Forum

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#215]
- Em criar um forum o campo de data está trocado o formato, o django está reconhecendo o dia como sendo mes e mes como sendo dia.
- Quando cria um novo tópico aparece que ele foi editado, más depois que é atualizado a página ele fica normal, sem o nome que foi editado, deveria aparecer que foi editado apenas depois que realmente foi editado.
- Quando cria um novo tópico não aparece a opção de editar, más depois que é atualizado a página ela aparece, deveria sempre está aparecendo a opção de editar.
- O botão load more answers está carregando apenas mais 2 respostas, deveria carregar pelo menos umas 5 respostas.
- O botão load more posts está carregando apenas mais 2 posts, deveria carregar pelo menos uns 5 posts.
- quando o botão load more posts está aparecendo e eu crio um novo post ele aparece depois do botão load more posts, assim o botão load more posts ficando entre dois posts, ele deveria ficar no final de todos os posts.

**Comment by Zambom** [comment]
Sobre o campo data: eu testei aqui e criou normalmente... Acho que você confundiu com o Create User, onde eu observei isso ocorrer...

**Comment by jailson-dias** [comment]
@Zambom quando eu edito um post ou uma resposta ela some do forum e só volta depois que eu atualizo a página e no modal de criar forum não está aparecendo o label e o placeholder de data

**Comment by jailson-dias** [comment]
ok
