### ISSUE TITLE
[BUG] Find Plain Text where was supposed to be Trans Template Tag

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#223]
- achar todos textos que estão sem a template Tag "trans"
- Generate files and check if the translation works for every page.

**Comment by jailson-dias** [comment]
@filipecmedeiros em subject > form_view_teacher.html existe textos que não estão com a tag trans e os arquivos de traduções de enquete, links, forum, files, exam, course e core não estão com a tradução, só está a versão em ingles ou no caso de courses que está faltando apenas algumas traduções.

**Comment by jailson-dias** [comment]
ok
