### ISSUE TITLE
[BUG] Profile

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#227]
- [x] O botão remover conta está redirecionando para "#" e não remove a conta de fato
- [x] O botão send email no menu lateral esquerdo em atualizar perfil não funciona
- [x] Para professor e aluno aparece o botão add user e quando ele é clicado dá erro 403 só que não era pra esse botão aparecer pq ele é só para admin
- [x] Em add user o cpf não é obrigatorio, mas se não for informado da erro e diz que aquele cpf já existe
- [x] Quando dá erro de submição dos dados ele salva todos os campos menos data de nascimento, assim tendo que digitar outra vez
- [x] quando eu clico em change password e tento trocar a senha do usuário ele redireciona para "http://localhost:8000/users/profile/change_password/" e fica com a tela branca.

**Comment by juliotoscano** [comment]
O profile não apresenta para o aluno ou professor o botao add user.

**Comment by juliotoscano** [comment]
@jailson-dias, no quinto topico, aonde exatamente está dando problema? testei quando fui cadastrar usuario ou dar update e não houve esse problema.

**Comment by juliotoscano** [comment]
@jailson-dias ficou de realizar as ultimas atividades.

**Comment by fbormann** [comment]
Essa issue está fechada pois os problemas foram resolvidos.
