### ISSUE TITLE
[BUG] Bugs gerais

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#228]
- Na tela de guest o botão de pesquisar não está funcionando, a parte de listar cursos não está no padrão da tela de meus cursos, o nome do professor sempre esta none(esta none pq quem fez este template colocou {{course.professors.name}}, só que professors é uma lista e lista não tem o atributo name), o template não extende de base(tendo assim muita repetição desnecessaria de código), quando clica em sair ele redireciona para home caso o usuário já esteja logado(era pra deslogar o usuário)
- O botão send da tela de reset password não está funcionando
- A opção remember email da tela de login não está funcionando
- Em detail course o dropdown do curso esta no meio da tela, era pra está no lado direito, o botão de create subject do dropdow abre um modal vazio, era pra redirecionar para criar um novo subject, o botão replicate course do dropdown não funciona, o botão remover do dropdown não funciona
- Em list category tem a opção de create category no menu de actions e no menu de category(era pra ter só um botão de create category)
- O nome da category esta muito colado com a lateral do card(era pra esta mais no centro)
- O dropdown não esta totalmente a direita, era pra está como está em meus cursos
- Quando o subject é criado pela interface o campo de category dentro dele fica none
- Quando um professor se escreve em outro curso como se fosse um aluno aparece as opções de criar curso e excluir curso no dropdown do curso e no caso de replicar quando ele clica em replicar aparece a mensagem de erro "'User' object has no attribute 'courses'" e quando ele clica em deletar ele consegue seguir todos os modals para deletar o curso só que não deleta, era pra não aparecer essas opções para ele, pois nesse curso ele pode ser apenas um aluno.

**Comment by matheuslins** [comment]
Tudo pra mim? :'( kkk @jailson é o Revilson e eu o Fixilson kkkkk

**Comment by fbormann** [comment]
@jailson-dias divide isso em diferentes tarefas, pow, isso foi o que sedraz arretou pra gente especificar melhor e tal

**Comment by fbormann** [comment]
Fechei esta issue pois é gigante e envolve várias issues de lugares diferentes, novas issues devem ser criadas ao verificar os problemas listados aqui.
