### ISSUE TITLE
[BUG] Course

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#229]
- [x] No model tem o campo de professors, só que no template tem apenas coordinator, assim deve trocar o nome no model para não confundir professor com coordenador.
- [x] No model tem uma imagem, só que ela não é usada no template, assim deve tirar ela do model e consequentimente tirando ela das telas de criar e editar curso ou encontrar um lugar para colocar ela dentro de detail course.
- [x] No model tem os campos init_register_date, end_register_date, init_date, end_date, content e objectivies que não estão sendo usado em nenhum lugar no template.

**Comment by juliotoscano** [comment]
@jailson-dias 
Duvida: Tenho que trocar a nomeclatura no MODEL para coordenador e tirar professor, é isso? Se sim, no modelo tem uma relação many-to-many. Devo trocar para deixar  um unico cordenador para o curso?

**Comment by juliotoscano** [comment]
Estou aguardando o exclarecimento da duvida.

**Comment by jailson-dias** [comment]
@juliotoscano é isso mesmo que tu tem que fazer, trocar o nome do campo e o tipo de relacionamento, de many-to-many para foreign key

**Comment by juliotoscano** [comment]
Esse ultimo topic eu entendi que esses atributos são importantes. Porem precisam ser mostrados ao usuario de alguma forma. Não definimos como isso seria apresentado. devido a isso vou deixar em aberto.
Obs: Depende também do planejamento do front end.

**Comment by juliotoscano** [comment]
Como sugerido na reuniao. Coloquei um atributo chamado Coordenator no model Course para identificarmos quais dos professores será o coordenador do curso. Dessa forma permanece o atributo coordenator e professors.

**Comment by juliotoscano** [comment]
Inseri as datas mostrando o inicio e fim de cadastro do curso na listagem de cursos porque normalmente quando se procura por cursos é isso que o aluno quer saber("sera que ainda posso me inscrever?")
Inseri os atributos "inicio de inscrição" e "fim de inscrição" no card de curso que é apresentado na listagem de cursos. Normalmente quando o aluno ver esses cursos é a primeira coisa que ele quer saber, se ainda da tempo de entrar para o curso.
Quando ele acessar o curso e mostrar os subjects, o aluno podera ver as datas "Começo de curso" e "Fim de cursos". Nesse card nao se faz necessario a data de inscrição pois ele ja se inscreveu.

**Comment by jailson-dias** [comment]
ok
