### ISSUE TITLE
[Procedure] Manage User

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#23]

**Comment by fbormann** [comment]
Eu ainda não consigo editar e/ou deletar um usuário, isso faz parte das funcionalidades desse Procedure?

**Comment by Zambom** [comment]
Faz não... Nessa era só a a listagem dos usuários (a "home users" digamos)

**Comment by fbormann** [comment]
Acabei de rever e está listando todos os users( exceto o próprio user que está procurando), close #23.
