### ISSUE TITLE
[Deploy] Colocar o amadeus no Heroku

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#230]
1. Colocar o amdeus no Heroku.
2. Deixar sem nenhum bug, possibilitando que o usuário crie uma conta, crie um curso e tudo mais sem nenhum problema.

**Comment by jailson-dias** [comment]
@fbormann @ailsoncgt qual é o link que eu acesso para ver se está tudo funcionando mesmo?

**Comment by fbormann** [comment]
Este é o nosso link de produção: https://amadeuslms.herokuapp.com/

lembre-se que é o da master pode não ter cois resolvida :v:

**Comment by jailson-dias** [comment]
ok
