### ISSUE TITLE
[Funcionalidade] Editor WYSIWYG

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#232]
- Colocar um editor WYSIWYG em todos os campo de texto area do amadeus
  1. criar curso
  2. editar curso
  3. criar topico
  4. editar topico
  5. criar subject
  6. editar subject
  7. criar enquete
  8. editar enquete
  9. criar forum
  10. editar forum
  11. criar post
  12. editar post
  13. resposta do forum
  14. editar resposta do forum
  15. outros

**Comment by filipecmedeiros** [comment]
@jailson-dias tava testando aqui e no fórum e na enquete não ficou legal...

**Comment by filipecmedeiros** [comment]
Assim como no post do fórum e nas respostas

**Comment by filipecmedeiros** [comment]
Está dando um bug quando vou editar tópico, pois o editor não está renderizando. Creio que seja por causa do modal, preciso averiguar melhor

**Comment by filipecmedeiros** [comment]
Consegui adicionar o summernote no modal pra editar tópico, mas tem um bug (antigo) que só está pegando o primeiro tópico. O botão de update do modal também não está presente e consequentemente não está salvando as alterações. Acredito que esse bug já seja de outra tarefa.

**Comment by jailson-dias** [comment]
ok
