### ISSUE TITLE
[Funcionalidade] Barra de busca

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#233]
- Criar uma barra de busca por arquivos e atividades semelhante ao facebook no navbar
  1. na campo de pesquisa é pra ter um placeholder com o nome "pesquisar arquivos (.pdf, outros) e/ou atividades" e está pesquisa tem que ser dentro dos cursos que o aluno ou o professor está inscrito.
  2. esta barra deve aparecer em todas as telas que tem o navbar

**Comment by filipecmedeiros** [comment]
A issue é apenas a modificação do template ou com a funcionalidade implementada, propriamente?

**Comment by jailson-dias** [comment]
ok
