### ISSUE TITLE
[Bug] Editar topico

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#234]
- Concertar o bug de quando o professor clica em editar topico, que buga a parte de create file, link e poll

**Comment by fbormann** [comment]
@juliotoscano  to pegando essa task porque as minhas estão todas em review, pra adiantar, valeu!

**Comment by juliotoscano** [comment]
os modais de link e file em edit nao funcionam.

**Comment by juliotoscano** [comment]
funciona; :+1: feito.
