### ISSUE TITLE
[Bug] Staticfile

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#236]
- Verificar todos os arquivos estáticos que estão faltando dentro da pasta staticfile do amadeus

**Comment by juliotoscano** [comment]
@jailson-dias Nessa atividade eu pensei que fosse para "arrumar" os arquivos statics que estavam duplicados e etc. Voce colocou que eu devo verificar arquivos faltantes. Não entendi muito bem isso.
Por fim, vc quer que eu coloque todos em uma unica page static? é isso?

**Comment by fbormann** [comment]
Sim, sim, são duas atividades diferentes @juliotoscano , uma são para os arquivos estáticos duplicados (que não estão sendo usados). Outra atividade é você sacar quais arquivos estão sendo coletados pra pasta "staticfiles" e quais não estão.

**Comment by juliotoscano** [comment]
os arquivos que estão em vendor são importantes? sao muitos arquivos com os mesmo conteudos de bootstrap? esse vendor tem haver com o heroku ou posso remover os que tem o mesmo conteudo?

**Comment by fbormann** [comment]
@juliotoscano não sei, você~tem de checar se os de vendor são usados nos templates ou não.

**Comment by juliotoscano** [comment]
Tudo bem. Temos muitos arquivos de static. Cada app tem uma. Essa atividade #236 quer que eu coloque todos os arquivos dentro de staticfile em amadeus? é isso? Todos dentro de uma unica pasta?

**Comment by fbormann** [comment]
@juliotoscano não, o django já faz isso com o comando "collectstatic". Foca na tarefa dos arquivos que não estão sendo usados, depois voltamos pra esta.

**Comment by jailson-dias** [comment]
ok
