### ISSUE TITLE
[Bug] Guest

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#238]
- [x] Concertar a página de guest para aparecer apenas para os usuarios que não estão logados
- [x] Concertar o layout para ficar parecido com o layout de my courses

**Comment by juliotoscano** [comment]
Eu entendi a segunda etapa da atividade. Nao entendi a primeira. Por favor explicar melhor o problema.

**Comment by juliotoscano** [comment]
@jailson-dias

**Comment by jailson-dias** [comment]
quando o usuário está logado aparece no menu tem meus cursos, todos os cursos e cursos que vai pra guest, aí é pra tirar esta 3 opção, pq não faz sentido ele poder ver todos os cursos e querer ir para uma página que só mostra os cursos publicos

**Comment by juliotoscano** [comment]
Nao vejo mais irregularidades no Layout. Entretanto quando eu click num course ele da erro.

**Comment by jailson-dias** [comment]
@juliotoscano nessa tela quando uma categoria tem 0 cursos mesmo assim ela aparece, era pra aparecer apenas se ela tiver algum curso para ser mostrado para o usuário

**Comment by jailson-dias** [comment]
o icone do titulo da página tb não está o do amadeus, tem que ajeitar ele

**Comment by juliotoscano** [comment]
![captura de tela de 2016-11-16 09-10-16](https://cloud.githubusercontent.com/assets/13151332/20346761/b712438c-abdc-11e6-8750-b73dc1f7027a.png)

**Comment by juliotoscano** [comment]
No meu aparece o Icone e não mostra categorias.
Obs: Quando clico em course ele da erro.

**Comment by juliotoscano** [comment]
@jailson-dias

**Comment by juliotoscano** [comment]
Erro resolvido.
Obs: Dava erro quando clicava no curso quando estava logado como guest.
Atividades pronta.

**Comment by gbl3** [comment]
OK
