### ISSUE TITLE
[Middleware] Logs

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#24]

**Comment by Zambom** [comment]
Feito com mixin e decorator ao invés de middleware. Me pareceu mais simples e "funcional" já que é possível enviar uma "mensagem" do que realmente foi feito pelo usuário naquela requisição para ser salva no log (por enquanto está salvando em arquivos de texto)

**Comment by fbormann** [comment]
Done and correct, Mixin for  CBV and decorator for FBV(function-based-views). Just need to add it to all other urls. Task for next sprint.
