### ISSUE TITLE
[Log] Avaliações

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#249]
Aluno:
 guarda o log de quando o aluno visualizou a avaliação de um determinado topico
 guarda o log de quando o aluno respondeu a avaliação de um determinado topico

Professor:
 guardar o log de quando o professor criou uma avaliação em um determinando topico

**Comment by fbormann** [comment]
Este log nem precisa ser checado pois as avaliações estão sendo reconstruídas, concorda @Zambom ? Se sim, fecha esta issue aqui.

**Comment by Zambom** [comment]
Realmente... Closing it.
