### ISSUE TITLE
[Test] Topic Chrome

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#287]

**Comment by Zambom** [comment]
- Ao clicar em editar o accordion tem que ser aberto (se estiver fechado);
- Não existe botão para salvar as alterações ao editar;
- O botão de remover está sem ação;
- Ajustar layout responsivo:
![image](https://cloud.githubusercontent.com/assets/5719854/20645009/8f435e7a-b42b-11e6-9cd4-cb65da274b6e.png)

**Comment by gbl3** [comment]
Teste documentado, OK.
