### ISSUE TITLE
[Test] Add user Chrome

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#288]

**Comment by Zambom** [comment]
![add_user_chrome_1](https://cloud.githubusercontent.com/assets/5719854/20451421/c9dc69fa-add7-11e6-81ae-6e4f33570c98.png)
![add_user_chrome_2](https://cloud.githubusercontent.com/assets/5719854/20451422/c9defb5c-add7-11e6-85fe-8797a76ddb2c.png)

- O layout "quebra" dependendo da resolução da tela;
- Estão aparecendo "dois quadrados" de checkbox para cada item desse tipo no formulário (apenas um funciona);
- O campo de data está sem o datepicker;
- O campo de CPF não está sendo validado. (CPF's usados no teste: 123.456.789-0 e 123.456.789-00);
- Se o formulário for submetido com erro, ao retornar para a correção dos dados inválidos ele não apresenta a data de nascimento preenchida anteriormente;
- O title da página está errado.

**Comment by fbormann** [comment]
Teste feito.
