### ISSUE TITLE
[Form] Course

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#29]
O formulário para criação de course esteja funcional, exiba erros, e sinalize restrições.

**Comment by matheuslins** [comment]
Teacher's Dashboard

**Comment by jailson0100** [comment]
ok

**Comment by thiagosoara** [comment]
PROBLEMAS:
1. ALL FIELDS REQUIRED. Alerta exibindo sem o cara preencher nada.
2.TextFields sem delimitação, usar outras cores para highlight
3. Datafield sem calendário
4. Select Categoria cropado
5. Imagefield sem indicação de onde clicar para fazer upload da imagem

6. REFAZER O CREATE COURSE., não estou conseguindo inserir curso. NameError (unicode erro)
