### ISSUE TITLE
[Test] File Chrome

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#295]

**Comment by Zambom** [comment]
- Ao tentar criar um File do tipo "*.pptx" foi retornado no javascript um erro 500; (Já registrado na issue: #405)
- Adicionar mensagem de sucesso após remover e editar;
- O link para visualizar o arquivo atual no formulário de edição não está clicável;
- Falta finalizar a página de visualização.

**Comment by fbormann** [comment]
Coloca o resultado deste teste lá no doc do Drive @Zambom

**Comment by gbl3** [comment]
Teste documentado na planilha, OK.
