### ISSUE TITLE
[Refactor] Urls

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#3]

**Comment by Zambom** [comment]
Faltou fazer o refactor do urls.py das apps "users" e "courses"

**Comment by matheuslins** [comment]
Só um erro de digitação aqui: url(r'^curso/(?P<slug>[\w_-]+)/modulos/**cirar**/$', views.CreateModView.as_view(), name='create_mods'), 

Ta cirar, acho que é **criar**, não?

Ahh, outra coisa, o acho que deveria ta tudo em inglês. Tipo: course/create etc.

**Comment by matheuslins** [comment]
ok
