### ISSUE TITLE
[Test] Link Firefox

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#314]

**Comment by juliotoscano** [comment]
Professor não consegui editar topico. Aluno não consegui vizualizar link.

**Comment by gbl3** [comment]
@juliotoscano estudante vendo link: 
![image](https://cloud.githubusercontent.com/assets/18217042/21054765/117dd8a4-be16-11e6-9fde-b29eec3f7a8e.png)

**Comment by gbl3** [comment]
Editar o tópico pelo professor também já é possível, portanto issue concluída.
