### ISSUE TITLE
[Test] File Safari

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#345]

**Comment by Zambom** [comment]
- Os arquivos criados aparecem alinhados à direita e sem o ícone: 
![image](https://cloud.githubusercontent.com/assets/5719854/20694917/430048c8-b5c7-11e6-86b3-b816b4a57015.png)
- Ao tentar criar um File do tipo "*.pptx" foi retornado no javascript um erro 500; (Já registrado na issue: #405)
- Adicionar mensagem de sucesso após remover e editar;
- O link para visualizar o arquivo atual no formulário de edição não está clicável;
- Falta finalizar a página de visualização.

**Comment by gbl3** [comment]
Teste documentado, OK.
