### ISSUE TITLE
[Test] Poll Safari

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#346]

**Comment by Zambom** [comment]
- Ao clicar para adicionar uma nova opção parte do layout desaparece:
![image](https://cloud.githubusercontent.com/assets/5719854/20694139/dadf7e4e-b5c1-11e6-9b31-d77f6c12c02e.png)
- Foi possível criar uma enquete com uma data limite anterior à atual;
- Colocar mensagens de sucesso no padrão do sistema;
- Colocar mensagem de sucesso ao remover;
- Ao clicar em "Resposta" nada acontece.

**Comment by fbormann** [comment]
Esse erro ainda acontece? testei aqui no safari, @Zambom  mas não vi ele desaparecer, a div cresce e a tela aumenta mas isso acontece mesmo, é algo que não da pra escapar.

**Comment by Zambom** [comment]
@fbormann o problema não é a div crescer, é o conteúdo 'sumir' e o usuário não conseguir acessá-lo mais...

**Comment by fbormann** [comment]
Tu pode descrever o caminho do teste pra eu testar tbm?

**Comment by Zambom** [comment]
@fbormann vai em um tópico, clica para adicionar um Poll e depois clica no botão de adicionar que fica antes da data de entrega... (não sei se isso já foi resolvido)

**Comment by fbormann** [comment]
Então, que informação some? Acho que foi resolvido porque é só o usuário da scroll down que tá tudo certo, ele consegue ver os outros botões .

**Comment by Zambom** [comment]
a informação que sumia era a que vinha antes...

**Comment by Zambom** [comment]
@fbormann se você reparar na imagem, a pergunta da enquete não aparece mais no modal...

**Comment by fbormann** [comment]
Ahh.. testei no safari aqui, agora tá de boas, confirma pra mim que por ai também naão tá sumindo, que fecho esta issue.
