### ISSUE TITLE
[Test] Link Safari

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#348]

**Comment by Zambom** [comment]
- Colocar o link para abrir em nova janela (aba);
- Ao clicar em editar topic logo após ter criado um link as opções "editar" e "remover" deste não são mostradas;
- A opção de "remover" retorna um erro 500;
- A imagem prévia do site não está sendo carregada;
- Com perfil de estudante, ao tentar acessar um link o javascript retorna o erro: "Uncaught ReferenceError: modal is not defined(…)";

**Comment by gbl3** [comment]
Problemas resolvidos, teste concluído.
