### ISSUE TITLE
Melhoria no Menu

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#360]
Falar com o UX sobre alguma melhoria que pode ser feita no menu e implementala

**Comment by filipecmedeiros** [comment]
@jailson-dias Foi informado que deverá ter um agrupamento "Users" com "Add user" e "Manage users", semelhante ao que tem em "Courses"

**Comment by fbormann** [comment]
apesar da descrição da issue (issues não podem ser criadas assim). @filipecmedeiros forneceu detalhes. E após checar utilizando um usuário "admin", funcionou.
