### ISSUE TITLE
[Funcionalidade] Replicar Subject

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#361]

**Comment by filipecmedeiros** [comment]
@jailson-dias essa issue já foi resolvida no commit [379323311d15b3af3d3448a137ec09d80775b8b0](https://github.com/amadeusproject/amadeuslms/commit/379323311d15b3af3d3448a137ec09d80775b8b0) de @Zambom (enquanto estávamos na reunião)

**Comment by gbl3** [comment]
ok
