### ISSUE TITLE
[Test] Maneger User Chrome

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#391]

**Comment by Zambom** [comment]
![manage_user_chrome](https://cloud.githubusercontent.com/assets/5719854/20583531/a9696da8-b1c9-11e6-9005-4d0ea75e67fd.png)

- O title da página está errado;
- As mensagens de sucesso não estão traduzidas;
- O layout "quebra" deixando um espaço em branco inutilizado no card;
- Após fazer a pesquisa seria interessante acrescentar ao breadcrumbs algo do gênero: "Você pesquisou por..." (devidamente traduzido).

**Comment by fbormann** [comment]
@Zambom , cria uma issue para cada um dos problemas, essa issue #423 tem de ser fechada e outras 4 criadas, sei que é chato mas facilita a correção de issues.

**Comment by fbormann** [comment]
Esta aqui está fechada pois o teste foi bem executado e levantou os erros. Se outro ciclo for ocorrer, criamos outra issue.
