### ISSUE TITLE
[BUG] Topic

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#400]
Após criado um tópico, quando você clica na opção "edit" não aparece a opção UPDATE. Além disso, depois desta correção, os botões "update" e "Back" devem ficar logo após a descrição do tópico

**Comment by Zambom** [comment]
Quando acessado com perfil de estudante, ao clicar para "fechar" o tópico os materiais e as atividades ainda ficam visíveis

**Comment by gbl3** [comment]
@juliotoscano isso aqui que falei

**Comment by fbormann** [comment]
Problema resolvido.
