### ISSUE TITLE
[BUG] Forum

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#406]
Ao acessar um fórum de uma subject na "Breadcrumbs" na aparece o no da subject, dificultando o retorno para a subject

**Comment by gbl3** [comment]
O breadcrumb está OK, aparecendo o nó da subject para poder retornar... 
![image](https://cloud.githubusercontent.com/assets/18217042/21080476/52ec516c-bf97-11e6-96a4-bbe10e57c048.png)

**Comment by gbl3** [comment]
OK
