### ISSUE TITLE
[BUG] Panel-Info

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#410]
No perfil de admin, semelhante ao que foi feito com as opções relacionadas com "Courses", deve ser criado um agrupamento "Users" com as opções "Add User" e "Manage Users"

**Comment by gbl3** [comment]
Resolvido no commit https://github.com/amadeusproject/amadeuslms/commit/21f2f60fb3bd1cfeda8deeb26ba5b1d7a66759d7

**Comment by jsedraz** [comment]
Filipe ainda vai finalizar esta issue com os ajustes que eu solicitei ontem.

**Comment by gbl3** [comment]
Ok @jsedraz

**Comment by filipecmedeiros** [comment]
Essa issue está duplicada e já foi resolvida na issue #360
