### ISSUE TITLE
[BUG] Create Category

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#414]
Quando se tenta criar uma categoria com o mesmo nome de outra que já existe, ao clicar em salvar o sistema não apresenta nenhuma reação, quando deveria emitir uma mensagem de erro do tipo "Já existe uma categoria com este nome".

**Comment by gbl3** [comment]
Faltando apenas padronizar a mensagem de erro.

**Comment by gbl3** [comment]
Done.
