### ISSUE TITLE
[BUG] Guest Page

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#416]
- O layout "quebra" dependendo do tamanho da tela (Ver imagens nas issues: #293 e #343);
- O title da página está errado;
- Alguns itens da página estão sem tradução;
- A busca da página está sem ação;
- Não faz sentido mostrar os ícones de mensagem e notificação (TopBar) se o usuário não estiver logado;
- Quando o usuário clica em um curso ele cai em uma tela de erro;
- Trocar o "AnonymousUser" por "Convidado" (devidamente traduzido) no nome do usuário se não houver usuário logado.

**Comment by Zambom** [comment]
@gbl3

**Comment by gbl3** [comment]
@Zambom o que deveria acontecer quando o usuário clicasse no curso?

**Comment by gbl3** [comment]
O que faltava ser resolvido foi feito por @juliotoscano , relacionado ao front também. Inclusive neste commit(a parte de clicar no curso dar erro): https://github.com/amadeusproject/amadeuslms/commit/de77742baa122c9cb79d7b7a033e3479500beb2d

**Comment by gbl3** [comment]
Done
