### ISSUE TITLE
[Bug]  Replicate Course Button

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#428]
Esse bug já foi mencionado na issue #228 , estou trazendo para cá pois é mais específico.

No "replicate courses" na url "courses/" não está funcionando, o erro aponta a falta do campo init_date no form.

**Comment by gbl3** [comment]
Aparentemente já está funcionando, não encontrei nenhum bug... 
![image](https://cloud.githubusercontent.com/assets/18217042/21026642/b64fcb78-bd74-11e6-8229-d002c770a7a3.png)
