### ISSUE TITLE
[BUG] Titulo das páginas

### ISSUE THREAD

**Issue by gbl3** [amadeusproject/amadeuslms#429]
Revisar as páginas que estão faltando um título e adicionar os títulos correspondentes.

**Comment by gbl3** [comment]
algumas páginas estão sem titulo ainda, como por exemplo as relacionadas ao perfil. Lembrando padrão de titulo: "Nome relacionado | Amadeus"

**Comment by fbormann** [comment]
Ainda está faltando o título das páginas em SubjectView, colocando esta tarefa para In Progress @filipecmedeiros

**Comment by filipecmedeiros** [comment]
@fbormann tu podia me mostrar exatamente onde? Aqui tá aparecendo normal...

**Comment by fbormann** [comment]
Agora foi, fechei esta issue.
