### ISSUE TITLE
[BUG] Edit Course (Chrome)

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#436]
- Ao realizar a edição de um curso o usuário é redirecionado para uma página de erro (ver imagem na issue: #285), mas a edição é feita;

**Comment by gbl3** [comment]
@Zambom eu editei um curso aqui e foi normal, foi redirecionado pra essa página: 
![image](https://cloud.githubusercontent.com/assets/18217042/20668638/f18e7c28-b556-11e6-979f-bcf3149ff085.png)

**Comment by gbl3** [comment]
OK
