### ISSUE TITLE
[Template] Atualizar Dashboard do Professor

### ISSUE THREAD

**Issue by matheuslins** [amadeusproject/amadeuslms#44]

**Comment by fbormann** [comment]
O que era pra ser feito nesta Task? Vi seus commits e confirmei que eles tão funcionando mas eram somente esses @Zambom ?

What needs to be done on this task? I saw your commits and confirmed that they are functional but were only these @Zambom ?

**Comment by Zambom** [comment]
It was to let the home page viewed by the teacher as defined by UxDesign (Image below) with a few changes mentioned by @thiagosoara (like put 'accordion' on 'manage courses')
![captura de tela de 2016-09-16 17-23-01](https://cloud.githubusercontent.com/assets/5719854/18600102/1d597096-7c32-11e6-9073-2e58a7e6a779.png)

**Comment by fbormann** [comment]
Great, I'll look into that as soon as possible.

**Comment by fbormann** [comment]
Ok, the only thing I'd change would be the color of your 'accordion'. To give a different focus. A shade of gray, maybe. For everything else, seems perfect. I'll close it.
