### ISSUE TITLE
[BUG] Menu Perfil

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#443]
- A opção de adicionar usuário aparece duas vezes no menu (Ver imagem nas issues: #340 e #289)

**Comment by filipecmedeiros** [comment]
Eu já tinha resolvido antes de ver essa issue nesse [https://github.com/amadeusproject/amadeuslms/commit/d90b319d4ddfc44ee17f86cefa93fd335241bb49](commit)

**Comment by fbormann** [comment]
Problema resolvido, closed
