### ISSUE TITLE
[Template] Atualizar Home do Administrador

### ISSUE THREAD

**Issue by matheuslins** [amadeusproject/amadeuslms#45]

**Comment by fbormann** [comment]
Essa Issue foi sobre atualizar a pesquisa, a paginação e os detalhes da tela "users/"? 


Was this issues about the research update, pagination and details on "users/" screen?

**Comment by Zambom** [comment]
No, this issue was about the main page of the system when user is an admin.

**Comment by fbormann** [comment]
It corrected my review about the accordion color. Now, the page seems correct.
