### ISSUE TITLE
[BUG] CRUD Link

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#453]
- Ao clicar em editar topic logo após ter criado um link as opções "editar" e "remover" deste não são mostradas.

**Comment by gbl3** [comment]
@jailson-dias depois tem como tu dar uma olhada nisso? Porque do jeito que ta ou quando cria aparece as opções de editar e remover tanto na tela de edit quanto na normal, ou o contrário... Dei uma olhada mas nao entendi como seria p lidar com isso

**Comment by jailson-dias** [comment]
#380

**Comment by gbl3** [comment]
OK
