### ISSUE TITLE
[BUG] O botão "Edit" em tópico não mostra o form de editar

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#465]
Ao clicar em editar tópico, um erro de javascript aparece:

![pasted image at 2016_12_09 01_00 pm](https://cloud.githubusercontent.com/assets/2985027/21057345/0f701840-be18-11e6-9148-a41fbe846c2b.png)

A issue estará solucionada quando o form de editar tópico aparecer.

**Comment by jailson-dias** [comment]
@fbormann já foi resolvido na issue #400

**Comment by gbl3** [comment]
OK
