### ISSUE TITLE
[Test] Register User

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#5]

**Comment by juliotoscano** [comment]
Revisado #5

**Comment by juliotoscano** [comment]
Faltou o test dando erro. "teste_register_erro"

**Comment by fbormann** [comment]
Comentei nos commits mas só pra registrar: os tests não estão aparecendo quando rodo no manage.py (eu li o código e parece ok mas saca lá)

**Comment by thiagosoara** [comment]
@ailsoncgt @gbl3 Não rodou o test, incompleto.

**Comment by ailsoncgt** [comment]
@thiagosoara , teste específico para register user:
python manage.py test core.tests.RegisterUserTestCase

**Comment by thiagosoara** [comment]
@ailsoncgt e @gbl3 Eu vi os testes, na verdade eu estava vendo o test da pasta users. Por que os teste de vcs estão no Core. Acho que deveria ficar em users. Tá certo agora. =)
