### ISSUE TITLE
[Log]  Notification Scroll

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#53]
[PT-BR]
 Fazer com que as notificações apareçam 5 a 5, e adicionar um botão "ver mais" que quando o usuário clicar, outras 5 notificações irão aparecer.

[EN- US]
Make all notifications appear 5 by 5, and add a "see more" button when the users click, it shows another 5 notifications.

**Comment by Zambom** [comment]
[PT-BR]
Eu testei aqui e ainda não deu scroll. Continua aparecendo todas as notificações de uma vez, não importa quantas existam, e o botão "ver mais" aparentemente está lá, mas não está visível.

[EN- US]
I tested here and it didn't scroll. It continues to appear all the notifications at once, no matter how many there are, and the 'see more' button is apparently there, but it's not visible

**Comment by fbormann** [comment]
I have split this task in other ones, more modular. So, this will become an Epic.

**Comment by ailsoncgt** [comment]
Depois de apertar 'See more' fica um espaço depois da 5ª notificação.
é pra ser assim?

![screenshot from 2016-10-10 11-47-29](https://cloud.githubusercontent.com/assets/18018868/19240241/df8465a8-8edf-11e6-9423-9365468f6740.png)

**Comment by fbormann** [comment]
Nem, isso é pq eu removo o elemento, preciso remover isso, não percebi. Pelo menos já sei a causa, valeu @ailsoncgt , bota pra Refactoring, por favor?

**Comment by ailsoncgt** [comment]
Done, @fbormann .
