### ISSUE TITLE
[Template] Add User Admin

### ISSUE THREAD

**Issue by ailsoncgt** [amadeusproject/amadeuslms#55]

**Comment by fbormann** [comment]
Template não tem mensagem de sucesso ao finalizar. Ao tentar adicionar um usuário como admin, não exibe mensagem de erro(se houve, porque testei adicionar um usuário e não rolou). 
Não tem máscara para CPF.
 E não tem javascript pra validar as máscaras sem precisar fazer a requisição.

**Comment by thiagosoara** [comment]
mesmos problemas de register user. Resolva lá que esse também ajeita.
