### ISSUE TITLE
[Template] Listar Cursos

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#57]
Fazer o template de listar cursos para professor e aluno, lembrando de colocar os links para profile, home e para professor e admin colocar a opção de criar curso, além de colocar a opção de editar e deletar o curso caso ele sejá um dos professores do curso ou admin.

**Comment by Zambom** [comment]
Lembro de ter sido comentado que os cursos seriam listados como "collapses" e não "sempre aberto" como está. Outra coisa, os botões de editar e deletar ficam em um menu no titlebar do curso...

**Comment by jailson-dias** [comment]
Além do que Zambom falou tb tem um texto abaixo do nome curso e os icones de editar e deletar que estão acima do botão de view course que não devia existir, como mostra esta [imagem](http://projetoamadeus.esy.es/img/lista-cursos-errada.png).

**Comment by thiagosoara** [comment]
@matheuslins Preciso que veja isso. A listagem de cursos não está funcionando para os usuários professor e aluno. Mesmo no admin ainda não está no padrão estabelecido no frontend.

**Comment by jailson-dias** [comment]
@matheuslins para admin está dando o seguinte erro "name 'queryset' is not defined" e para aluno e professor o collapse para aluno e professor está fechando todos os cursos ou abrindo todos os cursos, e era pra fechar e/ou abrir só o que for clicado.

**Comment by jailson-dias** [comment]
@matheuslins se a permissão do usuário que eu acessar está página for system_admin aí vai dá o seguinte erro "name 'queryset' is not defined"

**Comment by fbormann** [comment]
@matheuslins  saiu do projeto, então estou removendo suas issues.
