### ISSUE TITLE
[Template/View] Remember Password (New Password)

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#58]
Criar o template de submeter a nova senha enviada pelo e-mail

**Comment by gbl3** [comment]
@ifac0 seria interessante exibir uma mensagem informando que o e-mail foi enviado com sucesso! Além disso, vi que existe uma página reset done, mas quando clico para enviar o e-mail, não sou redirecionado para ela...

**Comment by ifac0** [comment]
@gbl3 vou da uma olhada nisso, já atualizei o template e vi também que ta dando erro ao enviar o email, vou tentar arrumar agora

**Comment by ifac0** [comment]
@gbl3 tudo arrumado, só tenho que falar com o pessoal de front para fazer os templates atualizados para as outras paginas.

**Comment by gbl3** [comment]
@ifac0 ta redirecionando, mas o email não está sendo enviado...!

**Comment by ifac0** [comment]
@gbl3  se tu olhar pelo terminal vai ver que ta realmente mandando, não sei o que ta acontecendo. hoje de tarde vou tentar corrigir.

**Comment by gbl3** [comment]
@ifac0 sim sim, acabei de ver aqui, realmente aparece o email no terminal, só não ta enviando, estranho...

**Comment by ifac0** [comment]
@gbl3 pronto, agora ta pegando. pode verificar e fechar.

**Comment by gbl3** [comment]
Done.

**Comment by gbl3** [comment]
#Closed
