### ISSUE TITLE
[Template] Atualizar Head

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#59]

**Comment by fbormann** [comment]
@amadeusproject/backend algueḿ lembra qual a mudança no header? @thiagosoara ?

**Comment by thiagosoara** [comment]
1. tirar aquele efeito de aumento da fonte no hover, sugiro colocar undeline mesmo no hover.
2. colocar ícone de logout
3. Colocar a logo do amadeus branca
