### ISSUE TITLE
[Procedure] Topic

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#61]
Consertar o template de topics (colocando como está o novo template de uxdesign) e colocar as opções de atividades e materiais como no amadeus antigo, além de criar a interação entre topics-atividades e topics-materiais.

**Comment by matheuslins** [comment]
Não consegui acessar a template

**Comment by fbormann** [comment]
tava In Progress ainda @matheuslins .

**Comment by fbormann** [comment]
Activities e Materiais já são acessíveis através dos tópicos.
