### ISSUE TITLE
[Procedure] Categoria de Subjects

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#62]
Criar o model de categoria para os subjects e fazer o processor de criar uma nova categoria e listar as categorias existentes.

**Comment by jailson-dias** [comment]
@matheuslins subject category é pra ser uma coisa que está dentro de um curso e não uma coisa totalmente independente como está, do jeito que está eu posso ter um subject sem ter nehuma categoria de subject e eu posso ter um subject category sem ter nenhum curso, era pra ser subject category dentro de curso e os subjects dentro de subject category (cursos > subject category > subject)

**Comment by jailson-dias** [comment]
@matheuslins dentro do view course os subjects devem ser exibidos dentro das categorias de subjects em uma expandable list, exibindo todas as categorias e clicando na categoria é exibido os subjetcs daquela categoria.

**Comment by jailson-dias** [comment]
@matheuslins não tem templates de editar, deletar e criar categoria de subjects, precisa ter template para tudo isso.

**Comment by jailson-dias** [comment]
@matheuslins onde estão os commits desta atividade

**Comment by fbormann** [comment]
@matheuslins  saiu do projeto, então estou removendo suas issues.
