### ISSUE TITLE
[Template] Categoria Subjects

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#63]
Criar o template de criar Categoria de subjects e o template de listar todas as categorias que já estão criadas.

**Comment by fbormann** [comment]
Tem nenhum template disto no UX-Design né? @juliotoscano @santojon @thiagosoara ? 
Acho que esse requisito veio durante a reunião do backend mesmo.

**Comment by thiagosoara** [comment]
Isso é um form bem básico, não passou pelo uxdesign pq quis concentrar nas atividades e talos.

**Comment by matheuslins** [comment]
acredito que não esteja atualizada de acordo com a template do ux

**Comment by fbormann** [comment]
closed this because @matheuslins  is fixing it in another issue.
