### ISSUE TITLE
Problema instalação via Docker

### ISSUE THREAD

**Issue by thiagosoara** [amadeusproject/amadeuslms#653]
Eu instalei na minha máquina Ubuntu Desktop 18.04 e não tive problemas. Porém quando fui instalar em um servidor do CIn, que está com o Ubuntu Server 18.04, não consegui subir o amadeus, ele retorna um em quanto monta a imagem do container:

amadeuslms_web_1 exited with code 1
amadeuslms_nginx_1 exited with code 1

A única coisa que fiz diferente do que está no tutorial foi que quando executo o comando "sudo docker-compose up --build ." não está pegando(mesmo executando da raiz do projeto, na pasta "/amadeuslms"). Porém quando tiro o ponto do final do comando, ou seja,  "sudo docker-compose up --build" ele carrega a imagem do container. Isso oi a única coisa que fiz diferente do tutorial

**Comment by fbormann** [comment]
O problema foi corrigido, o grande problema era a falta de um pacote no arquivo requirements.txt ,estou fechando este card.
