### ISSUE TITLE
[Test] File

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#69]
Criar os testes de arquivo postado, imagem do tipo de arquivo, se o arquivo está disponível para todos os alunos daquele subject e apenas para os alunos daquele subject (não pode ser visualizado por alunos que não estão inscritos naquele subject).

**Comment by ailsoncgt** [comment]
@jailson-dias , é essa issue ...

**Comment by jailson-dias** [comment]
ja existe outra issue para este teste
