### ISSUE TITLE
[Test] Edit User

### ISSUE THREAD

**Issue by Zambom** [amadeusproject/amadeuslms#7]

**Comment by fbormann** [comment]
Erros foram listados nos commits.

**Comment by fbormann** [comment]
Pessoal, @gbl3  mudou para Review e tu comitou novamente @ailsoncgt , esta tarefa tá pronta mesmo ou fica em review?

**Comment by thiagosoara** [comment]
@ailsoncgt aplicar as mesmas correções ditas em register user.

**Comment by thiagosoara** [comment]
@ailsoncgt @gbl3 
Tem um tal de Company Logo??? na tela de edit.
![image](https://cloud.githubusercontent.com/assets/766210/19081057/5728610a-8a2f-11e6-9d09-411ae58297eb.png)

**Comment by ailsoncgt** [comment]
@thiagosoara ...

python manage.py test core.tests.UpdateUserTestCase

**Comment by Zambom** [comment]
Rodei o test aqui e gerou esse erro: 'Key (user_id)=(1) is not present in table "users_user".' no test_update_ok...

**Comment by ailsoncgt** [comment]
@Zambom , rodou o teste unitário?

Porque aqui rodou tranquilo. Acabei de testar

**Comment by Zambom** [comment]
![captura de tela de 2016-10-06 22-25-57](https://cloud.githubusercontent.com/assets/5719854/19176183/b91ec99a-8c13-11e6-9bb6-6864f948dd87.png)
