### ISSUE TITLE
[Test] Deliver Exercises

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#72]
Criar os testes de arquivo submetido pelo aluno, se o arquivo está disponível para o aluno e o professor visualizar e apenas para eles dois (outro professor ou outro aluno não pode visualizar este arquivo) e criar o teste que o professor colocou a nota e apenas este professor(outro professor que não seja professor deste subject não pode colocar uma nota para este exercício.

**Comment by matheuslins** [comment]
Fechando pois já tem outra atividade como essa mais detalhada
