### ISSUE TITLE
[Template] Forum

### ISSUE THREAD

**Issue by jailson-dias** [amadeusproject/amadeuslms#73]
Criar o template do forum com as postagens e alguma resposta se tiver e fazer com que o professor do subject possa excluir alguma postagem e os alunos não possam excluir nenhuma postagem.

**Comment by fbormann** [comment]
@Zambom  o que tu já fez nesta task? Porque ela tá mal especificada, é capaz que tu já tenha feito várias da epic #87 e não saiba. Valeu!

**Comment by Zambom** [comment]
Tem a visualização do fórum, dos posts e das respostas dos posts, além dos forms de criação de post e de resposta.

**Comment by matheuslins** [comment]
Vi que ta bem feita. Só tem um detalhe...
<img width="1280" alt="screen shot 2016-10-05 at 3 24 55 pm" src="https://cloud.githubusercontent.com/assets/7929562/19126091/eb27aaa6-8b0f-11e6-80a1-98b87e5d1585.png">

Esse é um print da tela quando estou logado como estudante. Teoricamente não era para aparecer essas opções de editar e de deletar o comentário. Aparece apenas quando logado com o professor. 

Só isso mesmo!

**Comment by matheuslins** [comment]
Ahh, aqui também falta a mensagem de confirmação

**Comment by Zambom** [comment]
![captura de tela de 2016-10-11 19-53-00](https://cloud.githubusercontent.com/assets/5719854/19291527/2a750ce0-8fec-11e6-9627-fc255e85cb1a.png)

@matheuslins essa é a minha visualização quando eu entro com um usuário estudante... Eu acho que esse seu usuário tá marcado como "is_admin"...

**Comment by fbormann** [comment]
Confirmado por mim, o erro que tinha achado era sobre a data do Answer está errada ( o formato de exibição), foi arrumado.
