### ISSUE TITLE
[View/Template]  criação de Fórum

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#88]
- Template colocada dentro de "templates/forum";
- Template acessado através de uma URL
- Criar um Fórum corretamente

**Comment by matheuslins** [comment]
Ao especificar a data na template de criação de forum. O Widget formata a data no formato americano "mm/dd/yy". Quando o usuário tentar salvar o formulário, da um erro (Informe uma data/hora válida.), pois o formato certo teria que ser "dd/mm/yy".

**Comment by matheuslins** [comment]
Done!
