### ISSUE TITLE
[Test] Criar um Answer Post

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#89]
- Criar um AnswerPost utilizando a URL de criação correspondente.

**Comment by jailson-dias** [comment]
@filipecmedeiros este test deveria ter pelo menos uma verificação de quantidade de posts criados para ver se ele realmente foi criado e não subscreveu outro, além de ter uma opção criando com o professor e outra com o aluno.

**Comment by jailson-dias** [comment]
ok
