### ISSUE TITLE
[Template/View] Remoção de Entrega de Exercício

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#91]
- Uma URL que remove uma entrega de exercício.
- Mensagem de confirmação de Remoção.
- Mensagem de erro caso a remoção não aconteça.

**Comment by jailson-dias** [comment]
@matheuslins onde estão os commits desta atividade?

**Comment by gbl3** [comment]
@matheuslins eu vi que tem o código da view lá no views.py, mas não tem nenhum commit referenciando essa issue...
