### ISSUE TITLE
[Template/View] Criação de Entrega de Exercício

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#92]
- Acessível através de alguma URL
- Utilizar o modelo do UX-design(caso não tenha, amadeus antigo)
- Deve aparecer um feedback positivo caso a criação seja um sucesso, senão, uma mensagem de erro.

**Comment by jailson-dias** [comment]
@matheuslins onde estão os commits desta atividade?

**Comment by jailson-dias** [comment]
@matheuslins não tem como eu chegar nesta url e quando eu coloco a url dá erro nela.

**Comment by fbormann** [comment]
@matheuslins  saiu do projeto, então estou removendo suas issues.
