### ISSUE TITLE
[Model] Entrega de Exercício

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#94]
- Criar Model de Entrega de Exercício, seguir o modelo no amadeus antigo

**Comment by jailson-dias** [comment]
@matheuslins não está herdando de activity e não tem uma descrição como está no amadeus antigo, além disso não tem como saber qual foi o aluno que enviou o exercício.

**Comment by matheuslins** [comment]
Em andamento

**Comment by jailson-dias** [comment]
@matheuslins ainda está com o mesmo erro, vai resolver quando?

**Comment by gbl3** [comment]
@matheuslins alguma novidade?

**Comment by gbl3** [comment]
Exercise continua sem herdar de Activity

**Comment by fbormann** [comment]
@matheuslins  saiu do projeto, então estou removendo suas issues.
