### ISSUE TITLE
[View/Template] Edição de Fórum

### ISSUE THREAD

**Issue by fbormann** [amadeusproject/amadeuslms#97]
- Feedback de campos inválidos
- Feedback de modificação registrada
- Modificação ser de fato efetuada
- URL acessível.

**Comment by matheuslins** [comment]
Falta apenas o Feedback de modificação registrada. Uma mensagem de confirmação mesmo.

**Comment by Zambom** [comment]
Not sure if this corner alert is 100% visible...

**Comment by matheuslins** [comment]
<img width="1280" alt="screen shot 2016-10-07 at 4 09 28 pm" src="https://cloud.githubusercontent.com/assets/7929562/19202415/7e24fab8-8ca8-11e6-833d-cb482fcfe61e.png">

Tirou onda! Parabéns!

DONE!
